version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    networks:
      - monitoring
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - monitoring
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home

networks:
  monitoring:
    driver: bridge
